### PR TITLE
OTA from Github releases

### PR DESCRIPTION
**Pull request by stintel**
~~With these changes we can no longer OTA flash a self-built ota.bin. This should still be added. I'd also like to add an Updates tab with an overview of available releases with OTA assets, and local cache status. Thoughts?~~

### CODE REVIEW

**Comment by nikito** [comment]
Updates tab sounds like a good idea, could be good to have functionality similar to the config tab where we can do a push to all clients at once if we want to do a mass-OTA update.
Maybe we can also have the self-build OTA.bin merged into the lists along with the ones from GH, maybe prepended with something to signify it is local?
Could also be neat if there's some sort of system that can notify the user that a new build is available?

**Comment by stintel** [comment]
> Updates tab sounds like a good idea, could be good to have functionality similar to the config tab where we can do a push to all clients at once if we want to do a mass-OTA update.

We already thought of that (mass update). Not sure if it will be part of this PR though.

> Maybe we can also have the self-build OTA.bin merged into the lists along with the ones from GH, maybe prepended with something to signify it is local?

That's available now in the feature/ota_from_gh branch.

> Could also be neat if there's some sort of system that can notify the user that a new build is available?

I was thinking to add a widget for that in the Home tab.

**Comment by nikito** [comment]
Adding here in case it's needed for the readme, this command works to copy a locally built willow.bin into the docker container:
docker cp
./willow-ota-ESP32_S3_BOX.bin willow-application-server:app/static/o
ta/

First argument needs to be the path where the bin is (I ran from the same directory hence the ./ )

**Comment by stintel** [comment]
> Adding here in case it's needed for the readme, this command works to copy a locally built willow.bin into the docker container:

Thanks! Added to the README.

**Comment by stintel** [comment]
Did some refactoring. OTA files are now also in the was-storage container volume. Local OTA files are now under ota/local instead of just ota, so we don't need special handling for local releases compared to cached github releases. Also added a button to refresh the release info.

**Comment by nikito** [comment]
> Did some refactoring. OTA files are now also in the was-storage container volume. Local OTA files are now under ota/local instead of just ota, so we don't need special handling for local releases compared to cached github releases. Also added a button to refresh the release info.
> 
> I think this is good to go.

Just pulled latest container and get this at boot:
RuntimeError: Directory 'storage/ota' does not exist
Maybe a storage config argument needs to be added to the docker command?

**Comment by stintel** [comment]
> Just pulled latest container and get this at boot:
> RuntimeError: Directory 'storage/ota' does not exist
> Maybe a storage config argument needs to be added to the docker command?

I suspect this is because your was-storage volume existed already. Can you try wiping the storage volume and restarting the container?

**Comment by nikito** [comment]
> > Just pulled latest container and get this at boot:
> > RuntimeError: Directory 'storage/ota' does not exist
> > Maybe a storage config argument needs to be added to the docker command?
> 
> I suspect this is because your was-storage volume existed already. Can you try wiping the storage volume and restarting the container?

That worked, just need to repopulate configs, I should've backed them up lol. One smash detail, seems the releases page requires nvs to be populated it it breaks:
Screenshot_20230716-091924
Maybe need a condition to guide the user to do config first before going to this page and trying to refresh releases?

**Comment by stintel** [comment]
> One smash detail, seems the releases page requires nvs to be populated or it breaks:

Good catch. That's fixed now by hiding the refresh button if there is no user NVS config. I also moved the welcome note outside of the Home tab.

**Review by kristiankielhofner — APPROVED** [review]

**Pull request merged**
